### ISSUE TITLE
Automated test definition generation failing for non-buildable models

### ISSUE THREAD

**Issue by AnHeuermann** [pstelzig/MoPyRegtest#35]
# Problem description

The command line interface fails to generate test definition files if the Modelica model can't be translated/simulated.

**To Reproduce**

The automated test definition breaks for `MyLibrary.M`:

```modelica
package MyLibrary "Package"
  model M "Model"
    Real x(fixed=true, start=0);
    real y;  // Syntax error and number of variables not matching number of equations
  equation
    der(x) = -0.5*x;
  end M;
end MyLibrary;
```

```bash
> mopyregtest generate .CI/mopyregtest/ "TestM" . MyLibrary.M
Simulating model MyLibrary.M using the simulation tools: omc
Using simulation tool omc
/bin/sh: 1: ./MyLibrary.M: not found
Traceback (most recent call last):
  File "/home/USERNAME/.local/bin/mopyregtest", line 8, in <module>
    sys.exit(main())
  File "/home/USERNAME/.local/lib/python3.10/site-packages/mopyregtest/cli.py", line 136, in main
    parse_args(sys.argv[1:])
  File "/home/USERNAME/.local/lib/python3.10/site-packages/mopyregtest/cli.py", line 129, in parse_args
    args.func(args)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/mopyregtest/cli.py", line 48, in generate
    gen.generate_tests(test_folder, test_name, result_folder, references)
  File "/home/USERNAME/.local/lib/python3.10/site-packages/mopyregtest/generator.py", line 237, in generate_tests
    self._generate_reference(reference_folder=test_folder / "references",
  File "/home/USERNAME/.local/lib/python3.10/site-packages/mopyregtest/generator.py", line 175, in _generate_reference
    shutil.copyfile(pathlib.Path(tmp_res_folder) / res_file, str(pathlib.Path(reference_folder) / res_file))
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/MyLibrary.Mae09u5nf/MyLibrary.M_res.csv'
```

**System information (please complete the following information):**

 - OS: Ubuntu 22.04.3 LTS
 - OpenModelica: v1.23.0-dev-203-g5904d1ea84-cmake
 - Python: v3.10.12
 - MoPyRegtest: v0.5.0

# Desired behavior

Return a clear error message telling the user that:

  - the test definitions couldn't be generated for model `MyLibrary.M`.
  - print the error message from OpenModelica, giving a hint what the issue is and how to fix it.

The script should exit gracefully instead of failing to open some file and ideally clean up all half-generated files like `.CI/mopyregtest/references/MyLibrary.M_res.csv` and `.CI/mopyregtest/test_testm.py`.

So something like:

```bash
> mopyregtest generate .CI/mopyregtest/ "TestM" . MyLibrary.M
Failed to generate test definition for PNlib.TA:
Failed to build model:

[/path/to/MyLibrary/package.mo:4:5-4:11:writable] Error: Class real not found in scope M.

Aborting test definition generation.
Removing temporary files.
# exit code 1
```

**Comment by pstelzig** [comment]
Using the mechanisms from 9811d53a6943fcde5153f7d6499fb2113d2e58d2 used to solve #36, I now check if all necessary artifacts for running regression tests have been produced, i.e. 
1. a simulation binary has been produced that
2. produces a simulation result file to run the result comparison on.

If not, an AssertionError is raised in `RegressionTest._run_model`, which is caught in `Generator._generate_reference`, causing `mopyregtest generate` to exit with an error message. See 3b4761f6787d4e84a93a5d71f808a63fc1a4aa03

**Comment by pstelzig** [comment]
For instance, from the project's root folder, navigate to the tests folder where I put a package with flawed Modelica models (@AnHeuermann: Thanks for the inspiration in your minimum working example!)

```bash
cd tests/data
mopyregtest generate ./gentests doesnotbuild ./FlawedModels FlawedModels.DoesNotBuild
```

This will cause the CLI to exit with error code 1, and produce an output like 
```
Simulating model FlawedModels.DoesNotBuild using the simulation tools: omc
Using simulation tool omc
Failed to generate the test:

The expected simulation binary at /tmp/FlawedModels.DoesNotBuildoozmvhrl/FlawedModels.DoesNotBuild_res.csv does not exist. Please check the output from the simulation tool:

"/home/user/mopyregtest/tests/data/FlawedModels"
true
false
true
true
true
true
true
{FlawedModels}
true
"/tmp/FlawedModels.DoesNotBuildoozmvhrl"
true
true
true
true
true
true
true
true
true
false
{record OpenModelica.Scripting.ErrorMessage
    info = record OpenModelica.Scripting.SourceInfo
    filename = "/home/user/mopyregtest/tests/data/FlawedModels/package.mo",
    readonly = false,
    lineStart = 5,
    columnStart = 9,
    lineEnd = 5,
    columnEnd = 26
end OpenModelica.Scripting.SourceInfo;,
    message = "Variable x does not have any remaining equation to be solved in.
  The original equations were:
  Equation 1: der(x) = x * y, which needs to solve for y",
    kind = .OpenModelica.Scripting.ErrorKind.symbolic,
    level = .OpenModelica.Scripting.ErrorLevel.warning,
    id = 582
end OpenModelica.Scripting.ErrorMessage;,record OpenModelica.Scripting.ErrorMessage
    info = record OpenModelica.Scripting.SourceInfo
    filename = "",
    readonly = false,
    lineStart = 0,
    columnStart = 0,
    lineEnd = 0,
    columnEnd = 0
end OpenModelica.Scripting.SourceInfo;,
    message = "Too few equations, under-determined system. The model has 1 equation(s) and 2 variable(s).",
    kind = .OpenModelica.Scripting.ErrorKind.symbolic,
    level = .OpenModelica.Scripting.ErrorLevel.error,
    id = 32
end OpenModelica.Scripting.ErrorMessage;}

{"",""}
127
true
true
true
true
true
true
true
true
"/home/user/mopyregtest/tests/data/FlawedModels"
-1
"Error: Too few equations, under-determined system. The model has 1 equation(s) and 2 variable(s).
[/home/user/mopyregtest/tests/data/FlawedModels/package.mo:5:9-5:26:writable] Warning: Variable x does not have any remaining equation to be solved in.
  The original equations were:
  Equation 1: der(x) = x * y, which needs to solve for y
Error: Failed to open simulation result /tmp/FlawedModels.DoesNotBuildoozmvhrl/FlawedModels.DoesNotBuild_res.csv:
"
{}


Aborting test generation.
```
